name: write_slides
on: [push]
jobs:
  slides:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: why_is_python_slow
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: make install-texlive
      - name: Compile LaTeX
        run: make slides
      - name: Move
        run: mkdir -p github_artifacts && mv out/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  deploy:
    needs: [slides]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: Move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: slides
          force_orphan: true
